package splitum.presentation;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.util.Observable;
import java.util.Stack;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import splitum.business.SplitUM;
import splitum.business.apartamento.Morador;
import splitum.business.apartamento.MoradorExistenteException;
import splitum.business.apartamento.MoradorInexistenteException;
import splitum.business.apartamento.PasswordInvalidaException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class JFramePrincipal extends javax.swing.JFrame implements java.util.Observer {

    // mensagens
    private final static String TITULO = "$plitUM";
    private final static String ERRO_DADOS_INCOMPLETOS = "ERRO: preencha todos os campos.";
    
    private ImageIcon userIcon;
    private JPanelContaCorrente jPanelContaCorrente;
    private CardLayout cardLayout;
    private SplitUM splitUM;
    
    private Stack<JPanel> voltarPanels;
    private Stack<String> voltarCards;
    private Stack<Boolean> voltarMostrarAnterior;
    
    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal(SplitUM f) {
        initComponents();
        this.splitUM = f;
        
        this.splitUM.addObserver(this);

        this.loadUserIcon();
        this.jPanelContaCorrente = new JPanelContaCorrente(this, jPanelPrincipal, f);
        this.jPanelPrincipal.add(jPanelContaCorrente, "card_cc");
        this.jLabelVoltar.setForeground(Color.WHITE);
        this.jLabelLoginErro.setForeground(Color.WHITE);
        this.jLabelRegistoErro.setForeground(Color.WHITE);
        this.cardLayout = (CardLayout) jPanelPrincipal.getLayout();
        this.cardLayout.show(jPanelPrincipal, "card_inicial");
        this.voltarPanels = new Stack();
        this.voltarCards = new Stack();
        this.voltarMostrarAnterior = new Stack();
        
        this.jLabelNomeMorador.setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelInicial = new javax.swing.JPanel();
        jButtonInicialRegisto = new javax.swing.JButton();
        jButtonInicialLogin = new javax.swing.JButton();
        jButtonInicialSair = new javax.swing.JButton();
        jPanelLogin = new javax.swing.JPanel();
        jTextFieldLoginUsername = new javax.swing.JTextField();
        jButtonLoginOK = new javax.swing.JButton();
        jButtonLoginCancelar = new javax.swing.JButton();
        jLabelUsername = new javax.swing.JLabel();
        jLabelLoginErro = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordFieldLogin = new javax.swing.JPasswordField();
        jPanelRegisto = new javax.swing.JPanel();
        jLabelUsername2 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPassword2 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        JButtonRegistarGuardar = new javax.swing.JButton();
        jButtonRegistarCancelar = new javax.swing.JButton();
        jLabelRegistoErro = new javax.swing.JLabel();
        jPasswordFieldRegisto = new javax.swing.JPasswordField();
        jPanelTopo = new javax.swing.JPanel();
        jLabelVoltar = new javax.swing.JLabel();
        jLabelTituloSplitUM = new javax.swing.JLabel();
        jLabelNomeMorador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SplitUM");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 8000, 7000));
        setLocation(new java.awt.Point(100, 103));
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPrincipal.setForeground(new java.awt.Color(51, 51, 51));
        jPanelPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelPrincipal.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jPanelPrincipal.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanelPrincipal.setLayout(new java.awt.CardLayout());

        jPanelInicial.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInicial.setForeground(new java.awt.Color(51, 51, 51));
        jPanelInicial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelInicial.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanelInicial.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanelInicial.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanelInicial.setLayout(new java.awt.GridBagLayout());

        jButtonInicialRegisto.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonInicialRegisto.setText("Registar");
        jButtonInicialRegisto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicialRegistoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanelInicial.add(jButtonInicialRegisto, gridBagConstraints);

        jButtonInicialLogin.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonInicialLogin.setText("Iniciar Sessão");
        jButtonInicialLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicialLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanelInicial.add(jButtonInicialLogin, gridBagConstraints);

        jButtonInicialSair.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonInicialSair.setText("Sair");
        jButtonInicialSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicialSairActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanelInicial.add(jButtonInicialSair, gridBagConstraints);

        jPanelPrincipal.add(jPanelInicial, "card_inicial");

        jPanelLogin.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLogin.setForeground(new java.awt.Color(51, 51, 51));
        jPanelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelLogin.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanelLogin.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanelLogin.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanelLogin.setLayout(new java.awt.GridBagLayout());

        jTextFieldLoginUsername.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 20, 0);
        jPanelLogin.add(jTextFieldLoginUsername, gridBagConstraints);

        jButtonLoginOK.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButtonLoginOK.setText("OK");
        jButtonLoginOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginOKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 30, 20);
        jPanelLogin.add(jButtonLoginOK, gridBagConstraints);

        jButtonLoginCancelar.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButtonLoginCancelar.setText("Cancelar");
        jButtonLoginCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 30, 20);
        jPanelLogin.add(jButtonLoginCancelar, gridBagConstraints);

        jLabelUsername.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabelUsername.setText("Insira o seu username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 10;
        jPanelLogin.add(jLabelUsername, gridBagConstraints);

        jLabelLoginErro.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        jLabelLoginErro.setForeground(new java.awt.Color(255, 0, 0));
        jLabelLoginErro.setText("Erro: Dados de Login Inválidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanelLogin.add(jLabelLoginErro, gridBagConstraints);

        jLabelPassword.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabelPassword.setText("Insira a sua password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanelLogin.add(jLabelPassword, gridBagConstraints);

        jPasswordFieldLogin.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 20, 0);
        jPanelLogin.add(jPasswordFieldLogin, gridBagConstraints);

        jPanelPrincipal.add(jPanelLogin, "card_login");

        jPanelRegisto.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRegisto.setForeground(new java.awt.Color(51, 51, 51));
        jPanelRegisto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelRegisto.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanelRegisto.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanelRegisto.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanelRegisto.setLayout(new java.awt.GridBagLayout());

        jLabelUsername2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabelUsername2.setText("Insira o seu username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanelRegisto.add(jLabelUsername2, gridBagConstraints);

        jLabelNome.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabelNome.setText("Insira o seu nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanelRegisto.add(jLabelNome, gridBagConstraints);

        jLabelEmail.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabelEmail.setText("Insira o seu email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanelRegisto.add(jLabelEmail, gridBagConstraints);

        jLabelPassword2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabelPassword2.setText("Insira a sua password ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanelRegisto.add(jLabelPassword2, gridBagConstraints);

        jTextFieldUsername.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 15, 0);
        jPanelRegisto.add(jTextFieldUsername, gridBagConstraints);

        jTextFieldNome.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 15, 0);
        jPanelRegisto.add(jTextFieldNome, gridBagConstraints);

        jTextFieldEmail.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 15, 0);
        jPanelRegisto.add(jTextFieldEmail, gridBagConstraints);

        JButtonRegistarGuardar.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        JButtonRegistarGuardar.setText("Guardar");
        JButtonRegistarGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonRegistarGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanelRegisto.add(JButtonRegistarGuardar, gridBagConstraints);

        jButtonRegistarCancelar.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButtonRegistarCancelar.setText("Cancelar");
        jButtonRegistarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistarCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanelRegisto.add(jButtonRegistarCancelar, gridBagConstraints);

        jLabelRegistoErro.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        jLabelRegistoErro.setForeground(new java.awt.Color(255, 0, 0));
        jLabelRegistoErro.setText("Erro: Username já existe!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        jPanelRegisto.add(jLabelRegistoErro, gridBagConstraints);

        jPasswordFieldRegisto.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 15, 0);
        jPanelRegisto.add(jPasswordFieldRegisto, gridBagConstraints);

        jPanelPrincipal.add(jPanelRegisto, "card_registo");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanelPrincipal, gridBagConstraints);

        jPanelTopo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTopo.setMinimumSize(new java.awt.Dimension(600, 100));
        jPanelTopo.setPreferredSize(new java.awt.Dimension(800, 100));
        jPanelTopo.setLayout(new java.awt.GridBagLayout());

        jLabelVoltar.setBackground(new java.awt.Color(255, 255, 255));
        jLabelVoltar.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabelVoltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVoltar.setText("< Voltar");
        jLabelVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabelVoltar.setMaximumSize(null);
        jLabelVoltar.setMinimumSize(null);
        jLabelVoltar.setPreferredSize(null);
        jLabelVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVoltarMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelTopo.add(jLabelVoltar, gridBagConstraints);

        jLabelTituloSplitUM.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTituloSplitUM.setFont(new java.awt.Font("Jazz LET", 1, 48)); // NOI18N
        jLabelTituloSplitUM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloSplitUM.setText("$plitUM");
        jLabelTituloSplitUM.setToolTipText("");
        jLabelTituloSplitUM.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelTituloSplitUM.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabelTituloSplitUM.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabelTituloSplitUM.setPreferredSize(new java.awt.Dimension(100, 100));
        jLabelTituloSplitUM.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 150);
        jPanelTopo.add(jLabelTituloSplitUM, gridBagConstraints);

        jLabelNomeMorador.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabelNomeMorador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomeMorador.setText("user");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 150);
        jPanelTopo.add(jLabelNomeMorador, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 50;
        getContentPane().add(jPanelTopo, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInicialLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicialLoginActionPerformed
        clearPanelLogin();
        //displayUserIcon();
        cardLayout.show(jPanelPrincipal, "card_login");
    }//GEN-LAST:event_jButtonInicialLoginActionPerformed

    private void jButtonInicialRegistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicialRegistoActionPerformed
        clearPanelRegisto();
        cardLayout.show(jPanelPrincipal, "card_registo");       
    }//GEN-LAST:event_jButtonInicialRegistoActionPerformed

    private void jButtonLoginCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginCancelarActionPerformed
        //hideUserIcon();
        cardLayout.show(jPanelPrincipal, "card_inicial");
    }//GEN-LAST:event_jButtonLoginCancelarActionPerformed

    private void jButtonLoginOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginOKActionPerformed
        String username = jTextFieldLoginUsername.getText();
        String password = new String(jPasswordFieldLogin.getPassword());
        if(username.equals("") || password.equals("")) {
            jLabelLoginErro.setText(ERRO_DADOS_INCOMPLETOS);
            jLabelLoginErro.setForeground(Color.red);
        }
        else {
            try {
                splitUM.login(username, password);
                
                displayUserIcon();
                jPanelContaCorrente.init();
                cardLayout.show(jPanelPrincipal, "card_cc"); 
            }
            catch (MoradorInexistenteException ex) {
                
                jLabelLoginErro.setText("ERRO: " + ex.getMessage());
                jLabelLoginErro.setForeground(Color.red);
                jTextFieldUsername.setText("");
            }
            catch (PasswordInvalidaException ex) {
                jLabelLoginErro.setText("ERRO: " + ex.getMessage());
                jLabelLoginErro.setForeground(Color.red);
                jTextFieldUsername.setText("");
            }
        }
    }//GEN-LAST:event_jButtonLoginOKActionPerformed

    private void jButtonRegistarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistarCancelarActionPerformed
        cardLayout.show(jPanelPrincipal, "card_inicial"); 
    }//GEN-LAST:event_jButtonRegistarCancelarActionPerformed

    private void jButtonInicialSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicialSairActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButtonInicialSairActionPerformed

    private void JButtonRegistarGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonRegistarGuardarActionPerformed
        String username = jTextFieldUsername.getText();
        String nome = jTextFieldNome.getText();
        String password = new String(jPasswordFieldRegisto.getPassword());
        String email = jTextFieldEmail.getText();
        if(username.equals("") || nome.equals("") || password.equals("") || email.equals("")) {
            jLabelRegistoErro.setText(ERRO_DADOS_INCOMPLETOS);
            jLabelRegistoErro.setForeground(Color.red);
        }
        else {
            try {
                splitUM.registaUtilizador(username, password, nome, email);
                
                cardLayout.show(jPanelPrincipal, "card_inicial");
            } catch (MoradorExistenteException ex) {
                jLabelRegistoErro.setText("ERRO: " + ex.getMessage());
                jLabelRegistoErro.setForeground(Color.red);
                jTextFieldUsername.setText("");
            }
        }
    }//GEN-LAST:event_JButtonRegistarGuardarActionPerformed

    private void jLabelVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVoltarMouseClicked
        JPanel voltarPanel = voltarPanels.pop();
        CardLayout voltarCL = (CardLayout) voltarPanel.getLayout();
        voltarCL.show(voltarPanel, voltarCards.pop());
        if(!voltarMostrarAnterior.pop()) {
            esconderVoltar();
        } else {
            mostrarVoltar();
        }
    }//GEN-LAST:event_jLabelVoltarMouseClicked

    private void clearPanelLogin() {
        jTextFieldLoginUsername.setText("");
        jPasswordFieldLogin.setText("");
        jLabelLoginErro.setForeground(Color.WHITE);
    }

    private void clearPanelRegisto() {
        jTextFieldEmail.setText("");
        jTextFieldNome.setText("");
        jTextFieldUsername.setText("");
        jPasswordFieldRegisto.setText("");
        jLabelRegistoErro.setForeground(Color.WHITE);
    }
    
    private void loadUserIcon() {
        userIcon = new javax.swing.ImageIcon(getClass().getResource("/splitum/presentation/images/user_circle.png")); // load the image to a imageIcon
        Image image = userIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(100, 100,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        userIcon = new ImageIcon(newimg);  // transform it back
    }
    
    protected void hideUserIcon() {
        jLabelTituloSplitUM.setText(TITULO);
        jLabelTituloSplitUM.setIcon(null);
    }
    
    protected void displayUserIcon() {
        jLabelTituloSplitUM.setText("");
        jLabelTituloSplitUM.setIcon(userIcon);
    }
    
    // Botão voltar
    protected void pushVoltar(JPanel p, String card, Boolean mostrarAnterior) {
        voltarPanels.push(p);
        voltarCards.push(card);
        voltarMostrarAnterior.push(mostrarAnterior);
        mostrarVoltar();
    }
    
    protected void popVoltar() {
        JPanel voltarPanel = voltarPanels.pop();
        CardLayout voltarCL = (CardLayout) voltarPanel.getLayout();
        voltarCL.show(voltarPanel, voltarCards.pop());
        if(!voltarMostrarAnterior.pop()) {
            esconderVoltar();
        } else {
            mostrarVoltar();
        }
    }
    
    protected void clearVoltar() {
        while(!voltarPanels.empty()) voltarPanels.pop();
        while(!voltarCards.empty()) voltarCards.pop();
        while(!voltarMostrarAnterior.empty()) voltarMostrarAnterior.pop();
        esconderVoltar();
    }
    
    protected void mostrarVoltar() {
        jLabelVoltar.setForeground(Color.BLACK);
    }
    
    protected void esconderVoltar() {
        jLabelVoltar.setForeground(Color.WHITE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonRegistarGuardar;
    private javax.swing.JButton jButtonInicialLogin;
    private javax.swing.JButton jButtonInicialRegisto;
    private javax.swing.JButton jButtonInicialSair;
    private javax.swing.JButton jButtonLoginCancelar;
    private javax.swing.JButton jButtonLoginOK;
    private javax.swing.JButton jButtonRegistarCancelar;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelLoginErro;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeMorador;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPassword2;
    private javax.swing.JLabel jLabelRegistoErro;
    private javax.swing.JLabel jLabelTituloSplitUM;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelUsername2;
    private javax.swing.JLabel jLabelVoltar;
    private javax.swing.JPanel jPanelInicial;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelRegisto;
    private javax.swing.JPanel jPanelTopo;
    private javax.swing.JPasswordField jPasswordFieldLogin;
    private javax.swing.JPasswordField jPasswordFieldRegisto;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldLoginUsername;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        Morador m;
        if((m=splitUM.getMoradorAutenticado()) != null) {
            jLabelNomeMorador.setText(m.getNome());
            jLabelNomeMorador.setForeground(Color.BLACK);
        }
        else {
            jLabelNomeMorador.setForeground(Color.WHITE);
        }
    }
}
