/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splitum.presentation;

import java.awt.CardLayout;
import java.util.Observable;
import javax.swing.JPanel;
import splitum.business.SplitUM;
import splitum.business.apartamento.Morador;

public class JPanelContaCorrente extends javax.swing.JPanel implements java.util.Observer {

    private CardLayout cardLayout;
    private JPanelAdicionarDespesa jPanelAdicionarDespesa;
    private SplitUM splitUM;
    private JPanel jPanelPrincipal;
    private JPanelPerfil jPanelPerfil;
    private JFramePrincipal mainFrame;
    private JPanelDepositar jPanelDepositar;
    private JPanelApagarConta jPanelApagarConta;
    private JPanelApartamento jPanelApartamento;
    private JPanelVerDespesas jPanelVerDespesas;
    private JPanelHistorico jPanelHistorico;
    private JPanelAusentar jPanelAusentar;
    
    /**
     * Creates new form NewJPanel
     */
    public JPanelContaCorrente(JFramePrincipal mainFrame, JPanel jPanelPrincipal, SplitUM f) {
        initComponents();
        
        this.mainFrame = mainFrame;
        this.jPanelPrincipal = jPanelPrincipal;
        this.splitUM = f;
        
        this.splitUM.addObserver(this);
        
        jPanelAdicionarDespesa = new JPanelAdicionarDespesa(mainFrame, this, f);
        jPanelPerfil = new JPanelPerfil(this, f);
        jPanelDepositar = new JPanelDepositar(this, f);
        jPanelApagarConta = new JPanelApagarConta(mainFrame, jPanelPrincipal, this, f);
        jPanelApartamento = new JPanelApartamento(f);
        jPanelVerDespesas = new JPanelVerDespesas(mainFrame, this, f);
        jPanelHistorico = new JPanelHistorico(f);
        jPanelAusentar = new JPanelAusentar(this, f);
        this.add(jPanelAdicionarDespesa, "card_adiciona_despesa");
        this.add(jPanelPerfil, "card_perfil");
        this.add(jPanelDepositar, "card_depositar");
        this.add(jPanelApagarConta, "card_apagar_conta");
        this.add(jPanelApartamento, "card_apartamento");
        this.add(jPanelVerDespesas, "card_ver_despesas");
        this.add(jPanelHistorico, "card_historico");
        this.add(jPanelAusentar, "card_ausentar");
        
        this.cardLayout = (CardLayout) this.getLayout();
        this.cardLayout.show(this, "card_cc_inicial");
    }
    
    protected void init() {
        Morador morador = splitUM.getMoradorAutenticado();

        this.cardLayout.show(this, "card_cc_inicial");
        this.jTextFieldValorSaldo.setText(splitUM.getContaCorrente() + " € ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelContaCorrenteInicio = new javax.swing.JPanel();
        jLabelSaldo = new javax.swing.JLabel();
        jTextFieldValorSaldo = new javax.swing.JTextField();
        jButtonVerPerfil = new javax.swing.JButton();
        JButtonVerApartamento = new javax.swing.JButton();
        jButtonConsultarHistoricoConta = new javax.swing.JButton();
        jButtonApagarConta = new javax.swing.JButton();
        jButtonAdicionarDespesa = new javax.swing.JButton();
        jButtonVerDespesas = new javax.swing.JButton();
        jButtonDepositar = new javax.swing.JButton();
        jButtonAusentar = new javax.swing.JButton();
        jButtonTerminarSessao = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new java.awt.CardLayout());

        jPanelContaCorrenteInicio.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContaCorrenteInicio.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jPanelContaCorrenteInicio.setMinimumSize(new java.awt.Dimension(649, 500));
        jPanelContaCorrenteInicio.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanelContaCorrenteInicio.setLayout(new java.awt.GridBagLayout());

        jLabelSaldo.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabelSaldo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelSaldo.setText("Saldo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 10, 30);
        jPanelContaCorrenteInicio.add(jLabelSaldo, gridBagConstraints);

        jTextFieldValorSaldo.setEditable(false);
        jTextFieldValorSaldo.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextFieldValorSaldo.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldValorSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorSaldoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 10, 30);
        jPanelContaCorrenteInicio.add(jTextFieldValorSaldo, gridBagConstraints);

        jButtonVerPerfil.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButtonVerPerfil.setText("Ver o meu perfil");
        jButtonVerPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerPerfilActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(8, 30, 8, 30);
        jPanelContaCorrenteInicio.add(jButtonVerPerfil, gridBagConstraints);

        JButtonVerApartamento.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        JButtonVerApartamento.setText("Ver apartamento");
        JButtonVerApartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonVerApartamentoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(8, 30, 8, 30);
        jPanelContaCorrenteInicio.add(JButtonVerApartamento, gridBagConstraints);

        jButtonConsultarHistoricoConta.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButtonConsultarHistoricoConta.setText("Consultar histórico conta");
        jButtonConsultarHistoricoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarHistoricoContaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(8, 30, 8, 30);
        jPanelContaCorrenteInicio.add(jButtonConsultarHistoricoConta, gridBagConstraints);

        jButtonApagarConta.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButtonApagarConta.setText("Apagar Conta");
        jButtonApagarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarContaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(8, 30, 8, 30);
        jPanelContaCorrenteInicio.add(jButtonApagarConta, gridBagConstraints);

        jButtonAdicionarDespesa.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButtonAdicionarDespesa.setText("Adicionar despesa");
        jButtonAdicionarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarDespesaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(8, 30, 8, 30);
        jPanelContaCorrenteInicio.add(jButtonAdicionarDespesa, gridBagConstraints);

        jButtonVerDespesas.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButtonVerDespesas.setText("Ver despesas");
        jButtonVerDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerDespesasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(8, 30, 8, 30);
        jPanelContaCorrenteInicio.add(jButtonVerDespesas, gridBagConstraints);

        jButtonDepositar.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButtonDepositar.setText("Depositar");
        jButtonDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepositarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(8, 30, 8, 30);
        jPanelContaCorrenteInicio.add(jButtonDepositar, gridBagConstraints);

        jButtonAusentar.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButtonAusentar.setText("Ausentar");
        jButtonAusentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAusentarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(8, 30, 8, 30);
        jPanelContaCorrenteInicio.add(jButtonAusentar, gridBagConstraints);

        jButtonTerminarSessao.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButtonTerminarSessao.setText("Terminar Sessão");
        jButtonTerminarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerminarSessaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(8, 30, 8, 30);
        jPanelContaCorrenteInicio.add(jButtonTerminarSessao, gridBagConstraints);

        add(jPanelContaCorrenteInicio, "card_cc_inicial");
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldValorSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorSaldoActionPerformed

    private void jButtonAdicionarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarDespesaActionPerformed
        jPanelAdicionarDespesa.setAdicionarDespesa();
        jPanelAdicionarDespesa.init();
        this.cardLayout.show(this, "card_adiciona_despesa");
    }//GEN-LAST:event_jButtonAdicionarDespesaActionPerformed

    private void jButtonTerminarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerminarSessaoActionPerformed
        mainFrame.hideUserIcon();
        CardLayout mainCL = (CardLayout) jPanelPrincipal.getLayout();
        mainCL.show(jPanelPrincipal, "card_inicial");
        splitUM.logout();
    }//GEN-LAST:event_jButtonTerminarSessaoActionPerformed

    private void jButtonVerPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerPerfilActionPerformed
        this.jPanelPerfil.init();
        mainFrame.pushVoltar(this, "card_cc_inicial", false);
        this.cardLayout.show(this, "card_perfil");
    }//GEN-LAST:event_jButtonVerPerfilActionPerformed

    private void jButtonApagarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarContaActionPerformed
        jPanelApagarConta.init();
        this.cardLayout.show(this, "card_apagar_conta");
    }//GEN-LAST:event_jButtonApagarContaActionPerformed

    private void jButtonDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepositarActionPerformed
        this.jPanelDepositar.init();
        this.cardLayout.show(this, "card_depositar");
    }//GEN-LAST:event_jButtonDepositarActionPerformed

    private void JButtonVerApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonVerApartamentoActionPerformed
        this.jPanelApartamento.init();
        mainFrame.pushVoltar(this, "card_cc_inicial", false);
        this.cardLayout.show(this, "card_apartamento");
    }//GEN-LAST:event_JButtonVerApartamentoActionPerformed

    private void jButtonVerDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerDespesasActionPerformed
        this.jPanelVerDespesas.init();
        this.cardLayout.show(this, "card_ver_despesas");
    }//GEN-LAST:event_jButtonVerDespesasActionPerformed

    private void jButtonConsultarHistoricoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarHistoricoContaActionPerformed
        mainFrame.pushVoltar(this, "card_cc_inicial", false);
        this.jPanelHistorico.init();
        this.cardLayout.show(this, "card_historico");
    }//GEN-LAST:event_jButtonConsultarHistoricoContaActionPerformed

    private void jButtonAusentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAusentarActionPerformed
        this.jPanelAusentar.init();
        this.cardLayout.show(this, "card_ausentar");
    }//GEN-LAST:event_jButtonAusentarActionPerformed

    public JPanelAdicionarDespesa getjPanelAdicionarDespesa() {
        return jPanelAdicionarDespesa;
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonVerApartamento;
    private javax.swing.JButton jButtonAdicionarDespesa;
    private javax.swing.JButton jButtonApagarConta;
    private javax.swing.JButton jButtonAusentar;
    private javax.swing.JButton jButtonConsultarHistoricoConta;
    private javax.swing.JButton jButtonDepositar;
    private javax.swing.JButton jButtonTerminarSessao;
    private javax.swing.JButton jButtonVerDespesas;
    private javax.swing.JButton jButtonVerPerfil;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JPanel jPanelContaCorrenteInicio;
    private javax.swing.JTextField jTextFieldValorSaldo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        Morador morador = splitUM.getMoradorAutenticado();
        
        if (morador != null) {
            jTextFieldValorSaldo.setText(splitUM.getContaCorrente() + " € ");
        }
    }
}
