/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splitum.presentation;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import splitum.business.SplitUM;
import splitum.business.despesa.ExistemDividasExcpetion;

public class JPanelApagarConta extends javax.swing.JPanel {

    private SplitUM splitUM;
    private JFramePrincipal mainFrame;
    private JPanel jPanelPrincipal;
    private JPanel panelCC;
    
    /**
     * Creates new form JPanelApagarConta
     */
    public JPanelApagarConta(JFramePrincipal mainFrame, JPanel jPanelPrincipal, JPanel panelCC, SplitUM f) {
        initComponents();
        
        this.splitUM = f;
        this.mainFrame = mainFrame;
        this.jPanelPrincipal = jPanelPrincipal;
        this.panelCC = panelCC;
    }
    
    public void init() {
        jLabelErro.setForeground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelPergunta = new javax.swing.JLabel();
        jButtonApagarContaOK = new javax.swing.JButton();
        jButtonApagarContaCancelar = new javax.swing.JButton();
        jLabelErro = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jLabelPergunta.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabelPergunta.setText("Tem a certeza que deseja apagar a sua conta?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jLabelPergunta, gridBagConstraints);

        jButtonApagarContaOK.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButtonApagarContaOK.setText("OK");
        jButtonApagarContaOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarContaOKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(jButtonApagarContaOK, gridBagConstraints);

        jButtonApagarContaCancelar.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButtonApagarContaCancelar.setText("Cancelar");
        jButtonApagarContaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarContaCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(jButtonApagarContaCancelar, gridBagConstraints);

        jLabelErro.setFont(new java.awt.Font("Lucida Grande", 3, 16)); // NOI18N
        jLabelErro.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErro.setText("Não pode eliminar a conta, existem dívidas pendentes.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jLabelErro, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonApagarContaOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarContaOKActionPerformed
        try {
            splitUM.eliminaConta();
            mainFrame.hideUserIcon();
            CardLayout mainCL = (CardLayout) jPanelPrincipal.getLayout();
            mainCL.show(jPanelPrincipal, "card_inicial");
        } catch (ExistemDividasExcpetion ex) {
            jLabelErro.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButtonApagarContaOKActionPerformed

    private void jButtonApagarContaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarContaCancelarActionPerformed
        CardLayout cl = (CardLayout) panelCC.getLayout();
        cl.show(panelCC, "card_cc_inicial");
    }//GEN-LAST:event_jButtonApagarContaCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApagarContaCancelar;
    private javax.swing.JButton jButtonApagarContaOK;
    private javax.swing.JLabel jLabelErro;
    private javax.swing.JLabel jLabelPergunta;
    // End of variables declaration//GEN-END:variables
}
