/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splitum.presentation;

import java.util.List;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;
import splitum.business.SplitUM;
import splitum.business.contacorrente.Deposito;
import splitum.business.contacorrente.Movimento;
import splitum.business.contacorrente.PagamentoParcela;

public class JPanelHistorico extends javax.swing.JPanel {

    private SplitUM splitUM;
    private DefaultTableModel tableModel;
    
    /**
     * Creates new form JPanelHistorico
     */
    public JPanelHistorico(SplitUM f) {
        initComponents();
        
        this.splitUM = f;
        
        this.tableModel = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) { return false; }
            };
        
        String[] coluna = {"Descrição", "Data", "Movimento"};
        tableModel.setColumnIdentifiers(coluna);
        this.jTableHist.setModel(tableModel);
        this.jTableHist.setRowHeight(25);
    }

    protected void init() {
        
        tableModel.setRowCount(0);
        List<String[]> despesas = converteMovimentosEmTabela(splitUM.getMovimentosMorador());
        for(String[] row : despesas) {
            tableModel.addRow(row);
        }
        
        jLabelSaldoTotal.setText(splitUM.getContaCorrente() + " € ");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelHistTitulo = new javax.swing.JLabel();
        jScrollPaneHist = new javax.swing.JScrollPane();
        jTableHist = new javax.swing.JTable();
        jLabelSaldo = new javax.swing.JLabel();
        jLabelSaldoTotal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jLabelHistTitulo.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabelHistTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHistTitulo.setText("Histórico da Conta Corrente");
        jLabelHistTitulo.setMaximumSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(50, 20, 0, 20);
        add(jLabelHistTitulo, gridBagConstraints);

        jScrollPaneHist.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jScrollPaneHist.setMinimumSize(new java.awt.Dimension(200, 200));
        jScrollPaneHist.setPreferredSize(new java.awt.Dimension(600, 400));

        jTableHist.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTableHist.setFocusTraversalKeysEnabled(false);
        jTableHist.setFocusable(false);
        jTableHist.setMinimumSize(new java.awt.Dimension(200, 200));
        jTableHist.setPreferredSize(new java.awt.Dimension(300, 300));
        jTableHist.setRequestFocusEnabled(false);
        jTableHist.setShowHorizontalLines(false);
        jTableHist.setShowVerticalLines(false);
        jTableHist.setVerifyInputWhenFocusTarget(false);
        jScrollPaneHist.setViewportView(jTableHist);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 10, 50);
        add(jScrollPaneHist, gridBagConstraints);

        jLabelSaldo.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabelSaldo.setText("Saldo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 40, 50);
        add(jLabelSaldo, gridBagConstraints);

        jLabelSaldoTotal.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabelSaldoTotal.setText("0 €");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 40, 50);
        add(jLabelSaldoTotal, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelHistTitulo;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JLabel jLabelSaldoTotal;
    private javax.swing.JScrollPane jScrollPaneHist;
    private javax.swing.JTable jTableHist;
    // End of variables declaration//GEN-END:variables

    private List<String[]> converteMovimentosEmTabela(List<Movimento> movimentos) {
        return movimentos.stream().map(m -> {
            String[] linha = new String[3];
            linha[0] = m instanceof PagamentoParcela ? ((PagamentoParcela) m).getFatura().getDespesa().getDescricao() : "Depósito";
            linha[1] = m.getData().toString();
            linha[2] = m instanceof Deposito ? "+" + m.getValor() : "-" + m.getValor();
            
            return linha;
        }).collect(Collectors.toList());
    }
}
