/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splitum.presentation;

import splitum.business.SplitUM;
import splitum.business.apartamento.Morador;

public class JPanelPerfil extends javax.swing.JPanel {

    private SplitUM facade;
    private JPanelContaCorrente panelCC;
    private boolean editar;
    
    /**
     * Creates new form JPanelPerfil
     */
    public JPanelPerfil(JPanelContaCorrente panelCC, SplitUM f) {
        initComponents();
        this.facade = f;
        this.panelCC = panelCC;
    }
    
    protected void init() {
        editar = false;
        jTextFieldEmail.setVisible(false);
        jTextFieldNome.setVisible(false);
        jTextFieldPassword.setVisible(false);
        jTextFieldUsername.setVisible(false);
        
        Morador morador = facade.getMoradorAutenticado();
        
        jLabelNome1.setText(morador.getNome());
        jLabelEmail1.setText(morador.getEmail());
        jLabelUsername1.setText(morador.getUsername());
        jLabelPassword1.setText(morador.getPassword());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButtonEditarDados = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelNome1 = new javax.swing.JLabel();
        jLabelUsername1 = new javax.swing.JLabel();
        jLabelEmail1 = new javax.swing.JLabel();
        jLabelPassword1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldUsername = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new java.awt.GridBagLayout());

        jButtonEditarDados.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButtonEditarDados.setText("Editar Perfil");
        jButtonEditarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarDadosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        add(jButtonEditarDados, gridBagConstraints);

        jLabelNome.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabelNome.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        add(jLabelNome, gridBagConstraints);

        jLabelUsername.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabelUsername.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        add(jLabelUsername, gridBagConstraints);

        jLabelEmail.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabelEmail.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        add(jLabelEmail, gridBagConstraints);

        jLabelPassword.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabelPassword.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        add(jLabelPassword, gridBagConstraints);

        jLabelNome1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabelNome1.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        add(jLabelNome1, gridBagConstraints);

        jLabelUsername1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabelUsername1.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        add(jLabelUsername1, gridBagConstraints);

        jLabelEmail1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabelEmail1.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        add(jLabelEmail1, gridBagConstraints);

        jLabelPassword1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabelPassword1.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        add(jLabelPassword1, gridBagConstraints);

        jTextFieldNome.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextFieldNome.setText("Novo Nome");
        jTextFieldNome.setMinimumSize(new java.awt.Dimension(10, 100));
        jTextFieldNome.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        add(jTextFieldNome, gridBagConstraints);

        jTextFieldUsername.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextFieldUsername.setText("Novo Username");
        jTextFieldUsername.setMinimumSize(new java.awt.Dimension(10, 100));
        jTextFieldUsername.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        add(jTextFieldUsername, gridBagConstraints);

        jTextFieldEmail.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextFieldEmail.setText("Novo email");
        jTextFieldEmail.setMinimumSize(new java.awt.Dimension(10, 100));
        jTextFieldEmail.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        add(jTextFieldEmail, gridBagConstraints);

        jTextFieldPassword.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextFieldPassword.setText("Nova pass");
        jTextFieldPassword.setMinimumSize(new java.awt.Dimension(10, 100));
        jTextFieldPassword.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        add(jTextFieldPassword, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarDadosActionPerformed
        
        if(editar == false) {
            jTextFieldNome.setText(jLabelNome1.getText());
            jTextFieldUsername.setText(jLabelUsername1.getText());
            jTextFieldEmail.setText(jLabelEmail1.getText());
            jTextFieldPassword.setText(jLabelPassword1.getText());
            
            jTextFieldNome.setVisible(true);
            jTextFieldUsername.setVisible(true);
            jTextFieldEmail.setVisible(true);
            jTextFieldPassword.setVisible(true);
            
            jLabelNome1.setVisible(false);
            jLabelUsername1.setVisible(false);
            jLabelEmail1.setVisible(false);
            jLabelPassword1.setVisible(false);
            
            jButtonEditarDados.setText("Confirmar");
        } else {
            String novoNome = jTextFieldNome.getText();
            String novoUsername = jTextFieldUsername.getText();
            String novoEmail = jTextFieldEmail.getText();
            String novaPassword = jTextFieldPassword.getText();
            
            facade.atualizaDadosMorador(novaPassword, novoNome, novoEmail);
            //panelCC.setNomeMorador(novoNome);
            
            jLabelNome1.setText(novoNome);
            jLabelUsername1.setText(novoUsername);
            jLabelEmail1.setText(novoEmail);
            jLabelPassword1.setText(novaPassword);
            
            jTextFieldNome.setVisible(false);
            jTextFieldUsername.setVisible(false);
            jTextFieldEmail.setVisible(false);
            jTextFieldPassword.setVisible(false);
            
            jLabelNome1.setVisible(true);
            jLabelUsername1.setVisible(true);
            jLabelEmail1.setVisible(true);
            jLabelPassword1.setVisible(true);
            
            jButtonEditarDados.setText("Editar Perfil");
        }
        editar = !editar;
    }//GEN-LAST:event_jButtonEditarDadosActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarDados;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNome1;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPassword1;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelUsername1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
